"use client";
import { useMemo, useState } from "react";
import { calculateQuoteFollowUp, type QuoteFollowUpInputs } from "../lib/missed-call-calculator";

const defaults: QuoteFollowUpInputs = { quotationsPerMonth: 12, averageQuotationValue: 2500, followUpPercentage: 50 };
const currencies = { EUR: { symbol: "€", locale: "en-IE", label: "€ EUR — Euro" }, GBP: { symbol: "£", locale: "en-GB", label: "£ GBP — British Pound" }, USD: { symbol: "$", locale: "en-US", label: "$ USD — US Dollar" } } as const;
type CurrencyCode = keyof typeof currencies;
type InputKey = keyof QuoteFollowUpInputs;

function CalculatorInput({ id, label, hint, value, min, max, step, suffix, prefix, onChange }: { id: string; label: string; hint: string; value: number; min: number; max: number; step: number; suffix?: string; prefix?: string; onChange: (value: number) => void }) {
  const update = (nextValue: string) => { const parsed = Number(nextValue); onChange(Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : min); };
  return <div className="cost-field"><div className="cost-field-heading"><div><label htmlFor={`${id}-number`}>{label}</label><small id={`${id}-hint`}>{hint}</small></div><div className="cost-number-wrap">{prefix && <span aria-hidden="true">{prefix}</span>}<input id={`${id}-number`} type="number" inputMode="decimal" min={min} max={max} step={step} value={value} aria-describedby={`${id}-hint`} onChange={event => update(event.target.value)} />{suffix && <span aria-hidden="true">{suffix}</span>}</div></div><input className="cost-range" type="range" min={min} max={max} step={step} value={value} aria-label={`${label} slider`} onChange={event => update(event.target.value)} /><div className="cost-range-limits" aria-hidden="true"><span>{prefix}{min}{suffix}</span><span>{prefix}{max.toLocaleString("en-IE")}{suffix}</span></div></div>;
}

export default function MissedCallCostCalculator() {
  const [inputs, setInputs] = useState(defaults);
  const [currency, setCurrency] = useState<CurrencyCode>("EUR");
  const result = useMemo(() => calculateQuoteFollowUp(inputs), [inputs]);
  const money = useMemo(() => new Intl.NumberFormat(currencies[currency].locale, { style: "currency", currency, maximumFractionDigits: 0 }), [currency]);
  const quantity = useMemo(() => new Intl.NumberFormat(currencies[currency].locale, { maximumFractionDigits: 1 }), [currency]);
  const setValue = (key: InputKey, value: number) => setInputs(current => ({ ...current, [key]: value }));

  return <section className="cost-calculator sd-section" id="quote-calculator"><div className="cost-intro"><p className="mono coral">QUOTE FOLLOW-UP CALCULATOR</p><h2>How much quoted work may be waiting for follow-up?</h2><p>Use rough numbers to see the value of quotes that may not be getting followed up.</p></div><div className="cost-calculator-grid"><form className="cost-controls" onSubmit={event => event.preventDefault()}><div className="cost-currency"><div><label htmlFor="calculator-currency">Currency</label><small>Changes the symbol only. Values are not converted.</small></div><select id="calculator-currency" value={currency} onChange={event => setCurrency(event.target.value as CurrencyCode)}>{Object.entries(currencies).map(([code, details]) => <option key={code} value={code}>{details.label}</option>)}</select></div><CalculatorInput id="quotations" label="How many quotes do you send in a typical month?" hint="A rough monthly number is fine." value={inputs.quotationsPerMonth} min={0} max={100} step={1} onChange={value => setValue("quotationsPerMonth", value)} /><CalculatorInput id="quotation-value" label="Roughly, what is one quote worth?" hint="Think of a typical job you quote for." value={inputs.averageQuotationValue} min={0} max={50000} step={100} prefix={currencies[currency].symbol} onChange={value => setValue("averageQuotationValue", value)} /><CalculatorInput id="follow-up" label="About what percentage of those quotes do you follow up?" hint="If you follow up around half, choose 50%." value={inputs.followUpPercentage} min={0} max={100} step={5} suffix="%" onChange={value => setValue("followUpPercentage", value)} /></form><div className="cost-result" aria-live="polite"><p className="cost-result-lead">Based on the figures you entered:</p><div className="cost-flow"><p><strong>{inputs.quotationsPerMonth}</strong> quotes sent each month</p><span aria-hidden="true">↓</span><p>About <strong>{quantity.format(result.quotationsNotConsistentlyFollowedUp)}</strong> may not get followed up</p><span aria-hidden="true">↓</span><p>About <strong>{money.format(result.monthlyValueWithoutConsistentFollowUp)}</strong> in quotes may be waiting for follow-up each month</p><span aria-hidden="true">↓</span></div><div className="cost-total"><strong>{money.format(result.annualValueWithoutConsistentFollowUp)}</strong><span>Estimated yearly value of quotes not consistently followed up</span><p className="cost-context">This is quoted work awaiting follow-up — not money already lost, and not guaranteed revenue.</p></div><div className="cost-method"><h3>How we estimate this</h3><p>We use the number of monthly quotes, the typical quote value and the percentage you said you follow up.</p></div></div></div></section>;
}
