import type { Metadata } from "next";
import Link from "next/link";

const pages={
 dental:{business:"Bright Smile Dental",eyebrow:"AI RECEPTION FOR DENTAL",headline:"Every patient call, handled.",intro:"Sofia keeps the diary moving while your team stays focused on clinical care.",beats:[["09:14 — RESCHEDULE","I need to move my hygiene appointment.","Of course. Wednesday at 2:30 or Friday at 10?"],["09:16 — CANCEL","And cancel my son’s check-up tomorrow.","Done. Would you like me to find an after-school time next week?"],["09:18 — BOOK","Yes, after 4pm please.","Tuesday at 4:30 is available. I’ve booked it and sent both confirmations."]]},
 trades:{business:"SwiftFix Plumbing",eyebrow:"AI RECEPTION FOR TRADES",headline:"The call gets answered. You get the job.",intro:"Sofia identifies urgent work, captures the details and protects your time on site.",beats:[["11:21 — TRIAGE","A pipe has burst under the sink.","Turn off the stopcock if it’s safe. I’m checking your nearest emergency engineer."],["11:23 — DISPATCH","How soon can someone come?","Daniel can reach you in around 35 minutes. I’ll text his details now."],["11:29 — QUOTE","I also need a boiler quote.","I’ve logged that separately and arranged a survey for Thursday morning."]]},
 salon:{business:"The Loft Salon",eyebrow:"AI RECEPTION FOR SALONS",headline:"A full diary, without the interruptions.",intro:"Sofia knows every service, stylist and opening—then keeps the waitlist working too.",beats:[["10:04 — BOOK","Can I book colour with Mia?","Mia has Tuesday at 11 or Thursday at 3:30."],["10:08 — MOVE","Actually, can we move my cut?","Of course. I’ve moved it to the same Thursday at 5."],["10:15 — WAITLIST","Anything earlier for colour?","I’ve added you to Mia’s cancellation list and will text if a slot opens."]]},
 legal:{business:"Whitfield & Cole Law",eyebrow:"AI RECEPTION FOR LAW FIRMS",headline:"A professional first response, every time.",intro:"Sofia qualifies enquiries carefully and books consultations without giving legal advice.",beats:[["12:02 — INTAKE","I need help with a contract dispute.","I can arrange an initial consultation. Is this a business or personal contract?"],["12:06 — BOOK","Business. Tomorrow if possible.","Ms Cole has a 30-minute consultation at 3pm tomorrow."],["18:42 — AFTER HOURS","Is anyone available tonight?","The office is closed, but I’ve marked this urgent and the team will call at 8:30am."]]},
 restaurant:{business:"Marblehead Kitchen",eyebrow:"AI RECEPTION FOR RESTAURANTS",headline:"More covers. Fewer interruptions.",intro:"Sofia handles bookings, changes and dietary notes while your team looks after the room.",beats:[["18:11 — RESERVATION","A table for six this Saturday.","I have 7:15 or 8:45 available."],["18:12 — DIETARY NOTE","7:15. One guest is coeliac.","Noted. The kitchen will prepare accordingly."],["18:20 — CHANGE","Can we make it seven people?","Done. Your updated confirmation is on its way."]]}
} as const;
type Key=keyof typeof pages;
export function generateMetadata({params}:{params:{industry:string}}):Metadata{const p=pages[params.industry as Key];if(!p)return{title:"SmartDeskia"};return{title:`${p.business} | SmartDeskia Example`,description:p.intro,openGraph:{title:`${p.business} | ${p.headline}`,description:p.intro,images:[]},twitter:{title:`${p.business} | ${p.headline}`,description:p.intro,images:[]}}}
export default function IndustryPage({params}:{params:{industry:string}}){const p=pages[params.industry as Key];if(!p)return <main className="niche"><h1>Page not found.</h1><Link href="/">Back home</Link></main>;return <main className="niche"><header><Link className="sd-logo" href="/">SMART<span>DESK</span>IA<i></i></Link><Link href="/">← Back to all industries</Link></header><section className="niche-hero"><p className="mono coral">{p.eyebrow} · {p.business}</p><h1>{p.headline}</h1><p>{p.intro}</p><Link href="#call" className="coral-button">Hear the conversation <b>↓</b></Link></section><section className="niche-call" id="call"><p className="mono">A REALISTIC EXAMPLE CALL</p><h2>Three requests.<br/><em>One natural conversation.</em></h2><div>{p.beats.map((b,i)=><article key={b[0]}><span>{b[0]}</span><p><b>CALLER</b>{b[1]}</p><p><b>SOFIA</b>{b[2]}</p><i>{String(i+1).padStart(2,"0")}</i></article>)}</div></section><section className="niche-cta"><h2>Your business.<br/><em>Always answered.</em></h2><Link href="/#top" className="coral-button">Request a call <b>↗</b></Link></section></main>}
